meta_product_name: "Circuit"
meta_title: "Circuit - Dating app"
meta_description: "We make your online dating experience safer with face-to-face"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
